// Dati dimostrativi del prototipo. Persone, strutture e indirizzi sono FITTIZI.
// Corrispondono a supabase/seed.sql (stessi slug, servizi e disponibilità).
import type { Category, Provider } from "./types";

export const categories: Category[] = [
  { slug: "yoga-meditazione", name: "Yoga e meditazione", parentSlug: null, icon: "🧘", description: "Classi, lezioni private, mindfulness" },
  { slug: "massaggi-trattamenti", name: "Massaggi e trattamenti", parentSlug: null, icon: "💆", description: "Shiatsu, ayurveda, reiki, riflessologia" },
  { slug: "spa-terme", name: "SPA e terme", parentSlug: null, icon: "♨️", description: "Day spa, percorsi termali, coppie" },
  { slug: "naturopatia-consulenze", name: "Naturopatia e consulenze", parentSlug: null, icon: "🌿", description: "Stile di vita e benessere naturale" },
  { slug: "ritiri-eventi", name: "Ritiri ed eventi", parentSlug: null, icon: "⛰️", description: "Giornate e weekend nella natura" },
  { slug: "yoga", name: "Yoga", parentSlug: "yoga-meditazione" },
  { slug: "meditazione-mindfulness", name: "Meditazione e mindfulness", parentSlug: "yoga-meditazione" },
  { slug: "shiatsu", name: "Shiatsu", parentSlug: "massaggi-trattamenti" },
  { slug: "massaggio-ayurvedico", name: "Massaggio ayurvedico", parentSlug: "massaggi-trattamenti" },
  { slug: "reiki", name: "Reiki", parentSlug: "massaggi-trattamenti" },
  { slug: "riflessologia", name: "Riflessologia plantare", parentSlug: "massaggi-trattamenti" },
  { slug: "day-spa", name: "Day spa", parentSlug: "spa-terme" },
  { slug: "terme", name: "Terme", parentSlug: "spa-terme" },
  { slug: "naturopatia", name: "Naturopatia", parentSlug: "naturopatia-consulenze" },
  { slug: "ritiri", name: "Ritiri", parentSlug: "ritiri-eventi" },
];

export const cities = [
  { slug: "bologna", name: "Bologna", lat: 44.4949, lng: 11.3426 },
  { slug: "casalecchio-di-reno", name: "Casalecchio di Reno", lat: 44.476, lng: 11.277 },
  { slug: "imola", name: "Imola", lat: 44.3533, lng: 11.7141 },
  { slug: "porretta-terme", name: "Porretta Terme", lat: 44.155, lng: 10.977 },
  { slug: "camugnano", name: "Camugnano", lat: 44.22, lng: 11.089 },
];

const weekdays = (days: number[], start: string, end: string, serviceId?: string) =>
  days.map((weekday) => ({ weekday, start, end, serviceId }));

export const providers: Provider[] = [
  {
    slug: "studio-yoga-prana-bologna",
    kind: "venue",
    displayName: "Studio Yoga Prana",
    headline: "Hatha e Vinyasa yoga nel cuore di Bologna",
    bio: "Uno studio luminoso a due passi da Santo Stefano. Classi per tutti i livelli, lezioni private e percorsi di respirazione. Tappetini e supporti disponibili in sala.",
    verified: true,
    instantBooking: true,
    languages: ["it", "en"],
    categorySlugs: ["yoga", "meditazione-mindfulness"],
    location: { label: "Studio", address: "Via Santo Stefano 10", city: "Bologna", citySlug: "bologna", province: "BO", lat: 44.491, lng: 11.3487 },
    services: [
      { id: "e0000000-0000-0000-0000-000000000001", name: "Classe di Hatha yoga", description: "Classe di gruppo per tutti i livelli. Tappetini disponibili.", categorySlug: "yoga", durationMin: 75, slotStepMin: 75, priceCents: 1500, mode: "in_person", capacity: 12, cancellationPolicy: "flexible" },
      { id: "e0000000-0000-0000-0000-000000000002", name: "Lezione privata di yoga", description: "Lezione individuale personalizzata.", categorySlug: "yoga", durationMin: 60, slotStepMin: 60, priceCents: 5000, mode: "in_person", capacity: 1, cancellationPolicy: "moderate" },
    ],
    availability: [
      ...weekdays([1, 3, 5], "18:30", "19:45", "e0000000-0000-0000-0000-000000000001"),
      ...weekdays([2, 4], "09:00", "13:00", "e0000000-0000-0000-0000-000000000002"),
    ],
    reviews: [
      { authorName: "Francesca B.", rating: 5, body: "Ambiente accogliente e insegnanti attenti. Ideale anche per chi inizia.", date: "2026-09-12" },
      { authorName: "Davide L.", rating: 5, body: "La classe del mercoledì sera è diventata il mio appuntamento fisso.", date: "2026-08-30", reply: "Grazie Davide, ti aspettiamo!" },
      { authorName: "Sofia R.", rating: 4, body: "Bella pratica, sala un po' piena il venerdì.", date: "2026-08-02" },
    ],
    credentials: ["Insegnanti certificati Yoga Alliance RYT-500", "Assicurazione RC professionale"],
    palette: ["#9bb59a", "#e9dcc5"],
  },
  {
    slug: "giulia-neri-shiatsu",
    kind: "individual",
    displayName: "Giulia Neri",
    headline: "Operatrice shiatsu diplomata, 10 anni di esperienza",
    bio: "Trattamenti shiatsu per ritrovare equilibrio e rilassamento. Ogni incontro inizia con un breve colloquio per capire come stai. Lavoro su futon, con abbigliamento comodo.",
    verified: true,
    instantBooking: false,
    languages: ["it"],
    categorySlugs: ["shiatsu"],
    location: { label: "Studio", address: "Via di Corticella 20", city: "Bologna", citySlug: "bologna", province: "BO", lat: 44.51, lng: 11.344 },
    services: [
      { id: "e0000000-0000-0000-0000-000000000003", name: "Trattamento shiatsu", description: "Trattamento completo su futon, abbigliamento comodo.", categorySlug: "shiatsu", durationMin: 60, slotStepMin: 30, priceCents: 5500, mode: "in_person", capacity: 1, cancellationPolicy: "moderate" },
    ],
    availability: weekdays([1, 2, 3, 4, 5], "09:00", "19:00"),
    reviews: [
      { authorName: "Chiara E.", rating: 5, body: "Trattamento splendido, mi sono sentita accolta.", date: "2026-09-20" },
      { authorName: "Matteo G.", rating: 5, body: "Mani esperte e grande sensibilità. Consigliatissima.", date: "2026-09-01" },
    ],
    credentials: ["Diploma triennale di operatore shiatsu", "Iscritta ad associazione professionale (L. 4/2013)", "Assicurazione RC professionale"],
    palette: ["#c98b6b", "#f1e3d3"],
  },
  {
    slug: "terme-spa-appennino",
    kind: "venue",
    displayName: "Terme & SPA Appennino",
    headline: "Percorsi termali e massaggi tra i boschi dell'Appennino",
    bio: "Piscine termali, sauna finlandese, bagno turco e area relax con vista. Massaggi singoli e di coppia. A un'ora da Bologna, ideale per una giornata o un weekend.",
    verified: true,
    instantBooking: true,
    languages: ["it", "en"],
    categorySlugs: ["terme", "day-spa"],
    location: { label: "Terme", address: "Via delle Terme 1", city: "Porretta Terme", citySlug: "porretta-terme", province: "BO", lat: 44.155, lng: 10.977 },
    services: [
      { id: "e0000000-0000-0000-0000-000000000004", name: "Percorso termale (3 ore)", description: "Accesso a piscine termali, sauna, bagno turco e area relax. Accappatoio incluso.", categorySlug: "terme", durationMin: 180, slotStepMin: 60, priceCents: 4500, mode: "in_person", capacity: 20, cancellationPolicy: "flexible" },
      { id: "e0000000-0000-0000-0000-000000000005", name: "Massaggio di coppia", description: "Massaggio rilassante in cabina doppia.", categorySlug: "day-spa", durationMin: 50, slotStepMin: 60, priceCents: 12000, mode: "in_person", capacity: 1, cancellationPolicy: "strict" },
    ],
    availability: weekdays([1, 2, 3, 4, 5, 6, 7], "10:00", "22:00"),
    reviews: [
      { authorName: "Marco & Sara", rating: 5, body: "Weekend perfetto, il massaggio di coppia è stato il regalo di anniversario ideale.", date: "2026-09-15" },
      { authorName: "Ilaria T.", rating: 4, body: "Acqua bellissima, nel weekend c'è molta gente: meglio in settimana.", date: "2026-08-24" },
      { authorName: "Gianni P.", rating: 5, body: "Personale gentilissimo.", date: "2026-07-19" },
    ],
    credentials: ["Struttura autorizzata", "Personale qualificato"],
    palette: ["#7fa7b5", "#e3eef0"],
  },
  {
    slug: "marco-ferri-naturopata",
    kind: "individual",
    displayName: "Marco Ferri",
    headline: "Naturopata · consulenze in studio e online",
    bio: "Percorsi di benessere naturale su stile di vita, alimentazione consapevole e gestione dello stress. Le consulenze non sostituiscono il parere medico.",
    verified: true,
    instantBooking: true,
    languages: ["it", "en"],
    categorySlugs: ["naturopatia"],
    location: { label: "Studio", address: "Via Porrettana 50", city: "Casalecchio di Reno", citySlug: "casalecchio-di-reno", province: "BO", lat: 44.476, lng: 11.277 },
    services: [
      { id: "e0000000-0000-0000-0000-000000000006", name: "Primo colloquio naturopatico", description: "Incontro conoscitivo su stile di vita e obiettivi di benessere.", categorySlug: "naturopatia", durationMin: 60, slotStepMin: 60, priceCents: 6000, mode: "in_person", capacity: 1, cancellationPolicy: "moderate" },
      { id: "e0000000-0000-0000-0000-000000000007", name: "Consulenza online", description: "Videochiamata di approfondimento.", categorySlug: "naturopatia", durationMin: 45, slotStepMin: 45, priceCents: 4500, mode: "online", capacity: 1, cancellationPolicy: "flexible" },
    ],
    availability: weekdays([1, 2, 4], "14:00", "20:00"),
    reviews: [
      { authorName: "Elisa M.", rating: 5, body: "Molto chiaro e per nulla dogmatico. Consigli pratici e sostenibili.", date: "2026-09-08" },
    ],
    credentials: ["Diploma di naturopatia (corso triennale)", "Iscritto ad associazione professionale (L. 4/2013)"],
    palette: ["#8aa36f", "#eef0dc"],
  },
  {
    slug: "montovolo-retreat",
    kind: "venue",
    displayName: "Montovolo Retreat",
    headline: "Giornate di yoga e meditazione nella natura",
    bio: "Casa per ritiri sull'Appennino bolognese: giornate e weekend di yoga, meditazione e camminate consapevoli, con cucina vegetariana a km zero.",
    verified: true,
    instantBooking: true,
    languages: ["it"],
    categorySlugs: ["ritiri", "yoga"],
    location: { label: "Casa ritiri", address: "Località Montovolo", city: "Camugnano", citySlug: "camugnano", province: "BO", lat: 44.22, lng: 11.089 },
    services: [
      { id: "e0000000-0000-0000-0000-000000000008", name: "Giornata di yoga e meditazione", description: "Pratica mattutina, pranzo vegetariano, camminata meditativa e pratica serale.", categorySlug: "ritiri", durationMin: 420, slotStepMin: 420, priceCents: 8000, mode: "in_person", capacity: 15, cancellationPolicy: "strict" },
    ],
    availability: weekdays([6, 7], "09:00", "16:00", "e0000000-0000-0000-0000-000000000008"),
    reviews: [
      { authorName: "Roberta C.", rating: 5, body: "Un luogo magico, sono tornata a casa rigenerata.", date: "2026-09-21" },
      { authorName: "Andrea F.", rating: 5, body: "Organizzazione impeccabile e pranzo buonissimo.", date: "2026-08-10" },
    ],
    credentials: ["Insegnanti di yoga certificati", "Struttura ricettiva autorizzata"],
    palette: ["#6f8f7a", "#dfe8d8"],
  },
  {
    slug: "elena-rossi-mindfulness",
    kind: "individual",
    displayName: "Elena Rossi",
    headline: "Insegnante di meditazione e mindfulness",
    bio: "Sessioni individuali e percorsi di mindfulness per la gestione dello stress quotidiano, in studio o online.",
    verified: true,
    instantBooking: true,
    languages: ["it", "en", "fr"],
    categorySlugs: ["meditazione-mindfulness"],
    location: { label: "Studio", address: "Via Murri 30", city: "Bologna", citySlug: "bologna", province: "BO", lat: 44.483, lng: 11.365 },
    services: [
      { id: "e0000000-0000-0000-0000-000000000009", name: "Sessione individuale di mindfulness", description: "Pratiche guidate e strumenti per la vita quotidiana.", categorySlug: "meditazione-mindfulness", durationMin: 60, slotStepMin: 60, priceCents: 3500, mode: "in_person", capacity: 1, cancellationPolicy: "flexible" },
      { id: "e0000000-0000-0000-0000-000000000010", name: "Meditazione guidata online", description: "Sessione individuale in videochiamata.", categorySlug: "meditazione-mindfulness", durationMin: 45, slotStepMin: 45, priceCents: 2500, mode: "online", capacity: 1, cancellationPolicy: "flexible" },
    ],
    availability: weekdays([1, 2, 3, 4, 5, 6], "08:00", "12:00"),
    reviews: [
      { authorName: "Paola N.", rating: 5, body: "Voce calma e grande competenza. Mi ha aiutata a ritagliarmi spazi di respiro.", date: "2026-09-18" },
      { authorName: "Luca V.", rating: 4, body: "Ottime le sessioni online, comode in pausa pranzo.", date: "2026-09-03" },
    ],
    credentials: ["Formazione MBSR", "Assicurazione RC professionale"],
    palette: ["#a99bc4", "#ece6f3"],
  },
  {
    slug: "luca-bianchi-ayurveda",
    kind: "individual",
    displayName: "Luca Bianchi",
    headline: "Massaggio ayurvedico tradizionale",
    bio: "Massaggi Abhyanga e Padabhyanga con oli caldi, secondo la tradizione ayurvedica appresa in Kerala. Un'ora e un quarto per staccare davvero.",
    verified: true,
    instantBooking: true,
    languages: ["it", "en"],
    categorySlugs: ["massaggio-ayurvedico"],
    location: { label: "Studio", address: "Via San Donato 40", city: "Bologna", citySlug: "bologna", province: "BO", lat: 44.505, lng: 11.375 },
    services: [
      { id: "e0000000-0000-0000-0000-000000000011", name: "Massaggio Abhyanga", description: "Massaggio completo con oli caldi.", categorySlug: "massaggio-ayurvedico", durationMin: 75, slotStepMin: 15, priceCents: 7000, mode: "in_person", capacity: 1, cancellationPolicy: "moderate" },
      { id: "e0000000-0000-0000-0000-000000000012", name: "Padabhyanga (piedi)", description: "Trattamento dei piedi con coppetta di bronzo.", categorySlug: "massaggio-ayurvedico", durationMin: 40, slotStepMin: 20, priceCents: 3500, mode: "in_person", capacity: 1, cancellationPolicy: "moderate" },
    ],
    availability: weekdays([2, 3, 4, 5, 6], "10:00", "20:00"),
    reviews: [
      { authorName: "Valentina S.", rating: 5, body: "Il miglior massaggio della mia vita, senza esagerare.", date: "2026-09-25" },
    ],
    credentials: ["Formazione in massaggio ayurvedico (Kerala)", "Assicurazione RC professionale"],
    palette: ["#d6a04f", "#f6ead2"],
  },
  {
    slug: "sara-conti-reiki-imola",
    kind: "individual",
    displayName: "Sara Conti",
    headline: "Reiki e riflessologia plantare a Imola",
    bio: "Trattamenti di riequilibrio energetico e riflessologia plantare in un ambiente raccolto. Disponibile anche a domicilio a Imola e dintorni.",
    verified: true,
    instantBooking: false,
    languages: ["it"],
    categorySlugs: ["reiki", "riflessologia"],
    location: { label: "Studio", address: "Via Emilia 100", city: "Imola", citySlug: "imola", province: "BO", lat: 44.353, lng: 11.714 },
    services: [
      { id: "e0000000-0000-0000-0000-000000000013", name: "Trattamento Reiki", description: "Trattamento completo, sdraiati e vestiti.", categorySlug: "reiki", durationMin: 60, slotStepMin: 60, priceCents: 4000, mode: "in_person", capacity: 1, cancellationPolicy: "flexible" },
      { id: "e0000000-0000-0000-0000-000000000014", name: "Riflessologia plantare a domicilio", description: "Trattamento a casa tua (Imola e 10 km).", categorySlug: "riflessologia", durationMin: 50, slotStepMin: 60, priceCents: 5000, mode: "at_home", capacity: 1, cancellationPolicy: "moderate" },
    ],
    availability: weekdays([1, 3, 5], "15:00", "20:00"),
    reviews: [],
    credentials: ["Master Reiki (3° livello)", "Corso di riflessologia plantare"],
    palette: ["#c7889b", "#f5e4ea"],
  },
];
